// tests/pages/login.page.ts
// Page object per playwright-skill/pom/page-object-model.md:
// locators are readonly, methods are user actions, no expect() inside.
import type { Locator, Page } from '@playwright/test';
import { HomePage } from './home.page';

export class LoginPage {
  readonly heading: Locator;
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly passwordToggle: Locator;
  readonly submitButton: Locator;
  readonly signUpLink: Locator;
  readonly errorToast: Locator;

  constructor(private readonly page: Page) {
    this.heading = page.getByRole('heading', { name: 'Sign In' });
    this.emailInput = page.getByRole('textbox', { name: 'Email Address' });
    this.passwordInput = page.getByLabel('Password');
    // Locator generated by playwright-cli: the toggle's only accessible name is its icon.
    this.passwordToggle = page.getByRole('button', { name: 'eye' });
    this.submitButton = page.getByRole('button', { name: 'Sign in' });
    this.signUpLink = page.getByText('Sign up', { exact: true });
    // The store renders feedback as a role="status" toast.
    this.errorToast = page.getByRole('status');
  }

  async goto(): Promise<void> {
    await this.page.goto('/login', { waitUntil: 'domcontentloaded' });
  }

  /**
   * The login view is a lazily loaded chunk that can sit behind a spinner for
   * 10s+ on a cold hit. This is synchronisation, not an assertion, so it lives
   * here (see the POM guide's note on waitFor inside page objects).
   */
  async waitUntilReady(): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 30_000 });
  }

  async fillCredentials(email: string, password: string): Promise<void> {
    await this.emailInput.fill(email);
    await this.passwordInput.fill(password);
  }

  /**
   * Returns HomePage on success. Call only with valid credentials and only
   * when the login view was reached through the store (header icon): a direct
   * visit to /login redirects to /checkout instead.
   */
  async loginAs(email: string, password: string): Promise<HomePage> {
    await this.fillCredentials(email, password);
    await this.submitButton.click();
    await this.page.waitForURL((url) => url.pathname === '/');
    return new HomePage(this.page);
  }

  /** For negative tests: submits and stays on the login page. */
  async loginExpectingError(email: string, password: string): Promise<void> {
    await this.fillCredentials(email, password);
    await this.submitButton.click();
  }

  async togglePasswordVisibility(): Promise<void> {
    await this.passwordToggle.click();
  }

  async gotoSignUp(): Promise<void> {
    await this.signUpLink.click();
    await this.page.waitForURL('**/signup');
  }

  async sessionToken(): Promise<string | null> {
    return this.page.evaluate(() => localStorage.getItem('user_access_token'));
  }
}
